<?php
// $Id$

/**
 * This module provides a block with a link to the current page, hosted on
 * an alternate port. This should make it easy to bypass the Australian governments
 * proposed mandatory internet filter.
 *
 * This module is licenced under the GNU GPL version 2.
 */

/**
 * Implementaion of hook_block()
 *
 * This hook is /not/ ironic.
 */
function conroyfilter_block($op = 'list', $delta = 0, $edit = array()) {

  // List blocks on admin screen.
  //
  if ($op == 'list') {
    $blocks = array();
    $blocks[0] = array(
      'info' => 'Conroy Filter',
    );
    return $blocks;
  }

  // Show confguration.
  //
  if ($op == 'configure' && $delta == 0) {
    $form['port'] = array(
      '#type' => 'textfield',
      '#title' => t('Alternate Port'),
      '#description' => t('Which alternate port number does this web server serve content on? Leave blank or set to 0 to disable.'),
      '#default_value' => variable_get('conroyfilter_port', ''),
      '#maxlength' => 6,
      '#size' => 6,
    );
    return $form;
  }

  // Save configuration.
  //
  if ($op == 'save' && $delta == 0) {
    if (empty($edit['port'])) {
      variable_set('conroyfilter_port', '');
      return;
    }
    variable_set('conroyfilter_port', $edit['port']);
  }

  // View the block.
  //
  if ($op == 'view' && $delta == 0) {
    // Don't offer an alternate if the page is a result of a POST action.
    if ($_POST) {
      return;
    }

    $conroyfilter_port = variable_get('conroyfilter_port', '');
    if (!empty($conroyfilter_port)) {

      $filter = (intval($_SERVER['SERVER_PORT']) == 80) ? t('filter-free') : t('filtered');

      // Obtain the site url.
      $site = substr_replace(url('<front>', array('absolute' => TRUE, 'alias' => TRUE)), '', -1);
      // Chop off the port number, if set.
      $site = str_replace(':' . $_SERVER['SERVER_PORT'], '', $site);

      // Determine port number to link to, if any.
      $port = (intval($_SERVER['SERVER_PORT']) == 80) ? ':' . $conroyfilter_port : '';

      // Get the path of the page we want.
      $path = !empty($_REQUEST['q']) ? $_REQUEST['q'] : '';

      // Get the rest of the query_string, if present.
      $query = trim(str_replace('q='. $path, '', $_SERVER['QUERY_STRING']),'&');

      // Rewrite the path and stick the rest of the query string back on, if there is one.
      $path = url($path);
      if (!empty($query)) {
        $path .= (strpos($path, '?') !== FALSE ? '&' : '?') . $query;
      }

      // Make this all a pretty link, so we can eventually theme this.
      $link = $site . $port . $path;

      $subject = t('Conroy Filter');
      $content = t('A <a href="@link">mandatory internet @filter version</a> of this page is also available.',
        array('@filter' => $filter, '@link' => $link));

      return array('subject' => $subject, 'content' => $content);
    }
  }
}

/**
 * Implementation of hook_FORM_ID_alter().
 *
 * Inject a validate hook into the block form.
 */
function conroyfilter_form_block_admin_configure_alter(&$form, $form_state) {
  if ($form['module']['#value'] == 'conroyfilter' && $form['delta']['#value'] == 0) {
    $form['#validate'][] = 'conroyfilter_block_validate';
  }
}

/**
 * Validate function for the port number.
 */
function conroyfilter_block_validate($forme, &$form_state) {
  if (!empty($form_state['values']['port'])) {
    $port = (int) $form_state['values']['port'];
    if ($port < 1 || $port > 65535) {
      form_set_error('port', t('The port number must be a positive integer between 1 and 65535.'));
    }
  }
}
