<?php
// $Id$

/**
 * This module provides a block with a link to the current page, hosted on
 * an alternate port. This should make it easy to bypass the Australian governments
 * proposed mandatory internet filter.
 *
 * This module is licenced under the GNU GPL version 2.
 */

/**
 * Implementaion of hook_block()
 *
 * This hook is /not/ ironic.
 */
function conroyfilter_block($op = 'list', $delta = 0, $edit = array()) {

  // List blocks on admin screen.
  //
  if ($op == 'list') {
    $blocks = array();
    $blocks[0] = array(
      'info' => 'Conroy Filter',
    );
    return $blocks;
  }

  // Show confguration.
  //
  if ($op == 'configure' && $delta == 0) {
    $form['port'] = array(
      '#type' => 'textfield',
      '#title' => t('Alternate Port'),
      '#description' => t('Which alternate port number does this web server serve content on? Leave blank or set to 0 to disable.'),
      '#default_value' => variable_get('conroyfilter_port', ''),
    );
    $form['#validate'][] = 'conroyfilter_block_validate';
    return $form;
  }

  // Save configuration.
  //
  if ($op == 'save' && $delta == 0) {
    if (empty($edit['port'])) {
      variable_set('conroyfilter_port', '');
      return;
    }
    else {
      $port = intval($edit['port']);
      if ($port > 0 && $port < 65535) {
        variable_set('conroyfilter_port', $port);
      }
      else {
        form_set_error('port', t('The port number must be a positive integer between 1 and 65535.'));
      }
    }
  }

  // View the block.
  //
  if ($op == 'view' && $delta == 0) {
    $conroyfilter_port = variable_get('conroyfilter_port', '');
    if (!empty($conroyfilter_port)) {

      // Obtain the site url.
      $site = substr_replace(url('<front>', array('absolute' => TRUE, 'alias' => TRUE)), '', -1);

      // Chop the port number, if set.
      $site = str_replace(':' . $_SERVER['SERVER_PORT'], '', $site);

      $port = (intval($_SERVER['SERVER_PORT']) == 80) ? ':' . $conroyfilter_port : '';
      $page = url(implode('/', arg()));
      $filter = (intval($_SERVER['SERVER_PORT']) == 80) ? 'filter-free' : 'filtered';

      $subject = t('Conroy Filter');
      $content = t('A <a href="@site@port@page">mandatory internet @filter version</a> of this page is also available.',
        array('@filter' => $filter, '@site' => $site, '@port' => $port, '@page' => $page));

      return array('subject' => $subject, 'content' => $content);
    }
  }
}
